switch:
  - platform: command_line 
    switches:
      ac_salon_heater:
         friendly_name: 'Heater Living Room'
         unique_id: switch_ac_salon_heater
         command_on: >
             sh /opt/scripts/aircloud.sh on Séjour HEATING 22
         command_off: >
             sh /opt/scripts/aircloud.sh off Séjour HEATING 22
         command_state: >
             sh /opt/scripts/aircloud.sh powerstatus Séjour
         value_template: >
           {% if value == "ON" %}
           true
           {% else %}
           false
           {% endif %}
      ac_salon_cool:
         friendly_name: 'Cooler Living Room'
         unique_id: switch_ac_salon_cooler
         command_on: >
             sh /opt/scripts/aircloud.sh on Séjour COOLING 22
         command_off: >
             sh /opt/scripts/aircloud.sh off Séjour COOLING 22
         command_state: >
             sh /opt/scripts/aircloud.sh powerstatus Séjour
         value_template: >
           {% if value == "ON" %}
           true
           {% else %}
           false
           {% endif %}
sensor:
  - platform: command_line 
    name: "Temperature Living Room"
    unit_of_measurement: "°C"
    command: > 
        sh /opt/scripts/aircloud.sh roomtemperature Chambre
