switch:
  - platform: command_line 
    switches:
      ac_chambre_heater:
         friendly_name: 'Heater Chambre'
         unique_id: switch_ac_chambre_heater
         command_on: >
             sh /opt/scripts/aircloud.sh on Chambre HEATING 22
         command_off: >
             sh /opt/scripts/aircloud.sh off Chambre HEATING 22
         command_state: >
             sh /opt/scripts/aircloud.sh powerstatus Chambre
         value_template: >
           {% if value == "ON" %}
           true
           {% else %}
           false
           {% endif %}
      ac_chambre_cooler:
         friendly_name: 'Cooler Chambre'
         unique_id: switch_ac_chambre_cooler
         command_on: >
             sh /opt/scripts/aircloud.sh on Chambre COOLING 22
         command_off: >
             sh /opt/scripts/aircloud.sh off Chambre COOLING 22
         command_state: >
             sh /opt/scripts/aircloud.sh powerstatus Chambre
         value_template: >
           {% if value == "ON" %}
           true
           {% else %}
           false
           {% endif %}

sensor:
  - platform: command_line 
    name: "Temperature Chambre"
    unit_of_measurement: "°C"
    command: > 
        sh /opt/scripts/aircloud.sh roomtemperature Chambre