switch:
  - platform: command_line 
    switches:
      ac_chambre2_heater:
         friendly_name: 'Heater Chambre 2'
         unique_id: switch_ac_chambre2_heater
         command_on: >
             sh /opt/scripts/aircloud.sh on Chambre\ 2 HEATING 22
         command_off: >
             sh /opt/scripts/aircloud.sh off Chambre\ 2 HEATING 22
         command_state: >
             sh /opt/scripts/aircloud.sh powerstatus Chambre\ 2
         value_template: >
           {% if value == "ON" %}
           true
           {% else %}
           false
           {% endif %}
      ac_chambre2_cooler:
         friendly_name: 'Heater Chambre 2'
         unique_id: switch_ac_chambre2_cooler
         command_on: >
             sh /opt/scripts/aircloud.sh on Chambre\ 2 COOLING 22
         command_off: >
             sh /opt/scripts/aircloud.sh off Chambre\ 2 COOLING 22
         command_state: >
             sh /opt/scripts/aircloud.sh powerstatus Chambre\ 2
         value_template: >
           {% if value == "ON" %}
           true
           {% else %}
           false
           {% endif %}

sensor:
  - platform: command_line 
    name: "Temperature Chambre 2"
    unit_of_measurement: "°C"
    command: > 
        sh /opt/scripts/aircloud.sh roomtemperature Chambre\ 2